import type { Metadata } from "next";
import { Poppins ,Monomaniac_One } from "next/font/google";
import "./globals.css";

export const font2 = Monomaniac_One({ 
  subsets: ["latin"],
  weight:["400"]
 })

const font = Poppins({ subsets: ["latin"], weight: ["100" , "300" , "400" ,"600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
